name: sync-files

on:
  workflow_dispatch:
  push:
    paths:
      - 'toSync/**'
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync files
        env:
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.email "${GITHUB_OWNER}@users.noreply.github.com"
          git config --global user.name "${GITHUB_OWNER}"

          while IFS= read -r repo; do
              while IFS= read -r branch; do
                  echo "Updating ${repo}/${branch}..."
                  git clone -b "${branch}" "https://${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${repo}.git"
                  cp -a "${GITHUB_WORKSPACE}/file-templates/." "${GITHUB_WORKSPACE}/${repo}/"
                  cp -a "${GITHUB_WORKSPACE}/workflow-templates/." "${GITHUB_WORKSPACE}/${repo}/.github/workflows/"
                  cd "${GITHUB_WORKSPACE}/${repo}" || exit 1
                  git add .
                  if git commit -m "Updated some files [skip ci]"; then
                      git push
                  fi
                  cd "${GITHUB_WORKSPACE}" || exit 1
                  rm -rf "${GITHUB_WORKSPACE:?}/${repo}"
              done < <(curl -u "${GITHUB_OWNER}:${GITHUB_TOKEN}" -fsSL "https://api.github.com/repos/${GITHUB_OWNER}/${repo}/branches" | jq -r '.[] | select(.name!="master") | .name')
          done < <(curl -u "${GITHUB_OWNER}:${GITHUB_TOKEN}" -fsSL "https://api.github.com/users/${GITHUB_OWNER}/repos?per_page=1000" | jq -r '.[] | select(.topics[]=="docker-image") | .name')
